### PR TITLE
Helm based deployment #6

### PR DESCRIPTION
**Pull request by rflorenc**

### CODE REVIEW

**Comment by rflorenc** [comment]
### Uninstall
```
$ ./helm-wrapper.sh -r                                                                                                                                                       
uninstall.go:92: [debug] uninstall: Deleting drwatcher-operator
client.go:258: [debug] Starting delete for "drwatcher-operator" Service             
client.go:258: [debug] Starting delete for "drwatcher-operator" Deployment         
client.go:258: [debug] Starting delete for "drwatcher-operator-rolebinding" ClusterRoleBinding  
client.go:258: [debug] Starting delete for "drwatcher-operator-role" ClusterRole             
client.go:258: [debug] Starting delete for "drwatchers.dr.seven" CustomResourceDefinition
client.go:258: [debug] Starting delete for "drwatcher-operator" ServiceAccount                                                                                                  
uninstall.go:129: [debug] purge requested for drwatcher-operator
release "drwatcher-operator" uninstalled
```

### Install
```
$ ./helm-wrapper.sh -u
history.go:52: [debug] getting history for release drwatcher-operator
Release "drwatcher-operator" does not exist. Installing it now.
install.go:159: [debug] Original chart version: ""


client.go:108: [debug] creating 6 resource(s)
NAME: drwatcher-operator
LAST DEPLOYED: Thu Mar 18 17:39:38 2021
NAMESPACE: example
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: x
  tag: v0.1.0
imagePullSecrets: []
nameOverride: ""
podAnnotations:
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"
replicaCount: 1
resources: {}
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: drwatcher-operator

COMPUTED VALUES:
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: x
  tag: v0.1.0
imagePullSecrets: []
nameOverride: ""
podAnnotations:
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"
replicaCount: 1
resources: {}
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: drwatcher-operator

HOOKS:
MANIFEST:
---
# Source: drwatcher-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drwatcher-operator
  namespace: example
  labels:
    helm.sh/chart: drwatcher-operator-0.1.0
    app.kubernetes.io/name: drwatcher-operator
    app.kubernetes.io/instance: drwatcher-operator
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: drwatcher-operator/templates/crd/dr.crd_drwatchers.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: drwatcher-operator
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: drwatchers.dr.seven
spec:
  group: dr.seven
  names:
    kind: DRWatcher
    listKind: DRWatcherList
    plural: drwatchers
    singular: drwatcher
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: DRWatcher is the Schema for the drwatchers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DRWatcherSpec defines the desired state of DRWatcher
          properties:
            command:
              type: string
            readyForBackup:
              type: boolean
            schedule:
              description: Foo is an example field of DRWatcher. Edit DRWatcher_types.go
                to remove/update
              type: string
          type: object
        status:
          description: DRWatcherStatus defines the observed state of DRWatcher
          properties:
            phase:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
# Source: drwatcher-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: example
  name: drwatcher-operator-role
rules:
- apiGroups:
  - dr.seven
  resources:
  - drwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dr.seven
  resources:
  - drwatchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - "velero.io"
  resources:
    - backups
    - schedules
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - pods
    - secrets
    - serviceaccounts
  verbs:
    - '*'
---
# Source: drwatcher-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: example
  name: drwatcher-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drwatcher-operator-role
subjects:
  - kind: ServiceAccount
    name: drwatcher-operator
    namespace: example
---
# Source: drwatcher-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: drwatcher-operator
  namespace: example
  labels:
    helm.sh/chart: drwatcher-operator-0.1.0
    app.kubernetes.io/name: drwatcher-operator
    app.kubernetes.io/instance: drwatcher-operator
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: drwatcher-operator
    app.kubernetes.io/instance: drwatcher-operator
---
# Source: drwatcher-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drwatcher-operator
  namespace: example
  labels:
    helm.sh/chart: drwatcher-operator-0.1.0
    app.kubernetes.io/name: drwatcher-operator
    app.kubernetes.io/instance: drwatcher-operator
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drwatcher-operator
      app.kubernetes.io/instance: drwatcher-operator
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: drwatcher-operator
        app.kubernetes.io/instance: drwatcher-operator
    spec:
      serviceAccountName: drwatcher-operator
      securityContext:
        null
      containers:
        - name: drwatcher-operator
          securityContext:
            null
          image: "drwatcher-operator:v0.1.0"
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/drwatcher-operator
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {}

NOTES:
export POD_NAME=$(kubectl get pods --namespace example -l "app.kubernetes.io/name=drwatcher-operator,app.kubernetes.io/instance=drwatcher-operator" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace example port-forward $POD_NAME 8080:80
```

**Comment by rflorenc** [comment]
Good to merge confirmed with Radu.

**Review by radudd — COMMENTED** [review]
LGTM. One more thing you can do is to release the chart on Github pages: https://helm.sh/docs/topics/chart_repository/#github-pages-example

**Comment by rflorenc** [comment]
> LGTM. One more thing you can do is to release the chart on Github pages: https://helm.sh/docs/topics/chart_repository/#github-pages-example

Will check it out.

**Pull request merged**
